language: ruby
rvm:
- '2.2.5'
sudo: false
cache: bundler
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
  - PARALLEL_TEST_PROCESSORS=2
matrix:
  fast_finish: true
addons:
  postgresql: '9.4'
before_install:
- source ${TRAVIS_BUILD_DIR}/tools/ci/before_install.sh
before_script:
- source ${TRAVIS_BUILD_DIR}/tools/ci/before_script.sh
script:
- bundle exec rspec
after_script:
- source ${TRAVIS_BUILD_DIR}/tools/ci/after_script.sh
notifications:
  webhooks:
    urls:
    - ttps://webhooks.gitter.im/e/698e5e63a7c8d06717b2
    on_success: change
    on_failure: always
    on_start: never